<?php
require_once __DIR__.'/page.php';
require_once __DIR__.'/archive.php';
$admin=$_SESSION['role']==='admin'; $message='';
if($_SERVER['REQUEST_METHOD']==='POST') {
    try {
        if(!$admin) throw new RuntimeException('Only the administrator may change vendor accounts.');
        $id=(int)($_POST['id']??0);
        if(($_POST['action']??'')==='remove_vendor') { archiveVendor($pdo,$id); $message='Vendor removed. Existing payments are preserved.'; }
        elseif(($_POST['action']??'')==='edit') {
            $name=trim((string)($_POST['vendor_name']??'')); $stall=trim((string)($_POST['stall_number']??'')); $section=(int)($_POST['section_id']??0);
            $monthly=filter_var($_POST['monthly_rent']??'',FILTER_VALIDATE_FLOAT); $daily=filter_var($_POST['daily_rent']??'',FILTER_VALIDATE_FLOAT); $balance=filter_var($_POST['balance']??'',FILTER_VALIDATE_FLOAT); $due=$_POST['next_due_date']?:null;
            if(!$name || !$stall || strlen($name)>150 || strlen($stall)>50 || $monthly===false || $daily===false || $balance===false || min($monthly,$daily,$balance)<0 || max($monthly,$daily,$balance)>99999999.99) throw new RuntimeException('Enter valid vendor details and nonnegative rent and balance.');
            if($due && (!($date=DateTimeImmutable::createFromFormat('!Y-m-d',$due)) || $date->format('Y-m-d')!==$due)) throw new RuntimeException('Enter a valid due date.');
            $pdo->beginTransaction();
            $q=$pdo->prepare('SELECT id FROM sections WHERE id=? AND deleted_at IS NULL FOR UPDATE'); $q->execute([$section]); if(!$q->fetchColumn()) throw new RuntimeException('Select an available section.');
            $q=$pdo->prepare('SELECT id FROM vendors WHERE stall_number=? AND section_id=? AND deleted_at IS NULL AND id<>?'); $q->execute([$stall,$section,$id]); if($q->fetchColumn()) throw new RuntimeException('This stall is already assigned within this section.');
            $pdo->prepare('UPDATE vendors SET vendor_name=?,stall_number=?,section_id=?,monthly_rent=?,daily_rent=?,balance=?,next_due_date=? WHERE id=? AND deleted_at IS NULL')->execute([$name,$stall,$section,$monthly,$daily,$balance,$due,$id]);
            $pdo->commit(); $message='Vendor details saved.';
        }
    } catch(Throwable $e) { if($pdo->inTransaction())$pdo->rollBack(); $message=$e instanceof PDOException?'Could not save vendor details.':$e->getMessage(); }
}
$search=trim((string)($_GET['search']??'')); $section=(int)($_GET['section_id']??0); $status=(string)($_GET['status']??''); $paymentStatus=(string)($_GET['payment_status']??'');
$q=$pdo->prepare("SELECT v.*,u.status AS user_status,u.email,s.section_name,COALESCE(NULLIF(v.vendor_name,''),NULLIF(TRIM(CONCAT_WS(' ',u.first_name,u.last_name)),''),u.fullname) AS name,COALESCE(p.base_paid,0) AS base_paid,CASE WHEN u.status<>'active' OR v.status='inactive' THEN 'inactive' WHEN v.balance>0 AND v.next_due_date<CURDATE() THEN 'overdue' ELSE 'active' END AS account_status,CASE WHEN v.balance>0 AND v.next_due_date<CURDATE() THEN 'overdue' WHEN COALESCE(p.base_paid,0)>0 AND v.balance<=0 THEN 'paid' WHEN COALESCE(p.base_paid,0)>0 THEN 'partial' ELSE 'unpaid' END AS payment_status FROM vendors v JOIN users u ON u.id=v.user_id LEFT JOIN sections s ON s.id=v.section_id LEFT JOIN (SELECT vendor_id,SUM(amount_paid) AS base_paid FROM payments WHERE status='paid' AND payment_date BETWEEN DATE_FORMAT(CURDATE(),'%Y-%m-01') AND LAST_DAY(CURDATE()) GROUP BY vendor_id) p ON p.vendor_id=v.id WHERE v.deleted_at IS NULL AND u.deleted_at IS NULL AND (?=0 OR v.section_id=?) AND (v.vendor_name LIKE ? OR CONCAT_WS(' ',u.first_name,u.last_name) LIKE ? OR v.stall_number LIKE ? OR s.section_name LIKE ?) ORDER BY s.section_name,CAST(SUBSTRING_INDEX(v.stall_number,'-',-1) AS UNSIGNED),v.stall_number,v.id");
$like='%'.$search.'%'; $q->execute([$section,$section,$like,$like,$like,$like]); $rows=$q->fetchAll(PDO::FETCH_ASSOC);
$rows=array_values(array_filter($rows,fn($v)=>($status==='' || ($status==='paid'?$v['payment_status']==='paid':$v['account_status']===$status)) && ($paymentStatus==='' || $v['payment_status']===$paymentStatus)));
$sections=$pdo->query('SELECT * FROM sections WHERE deleted_at IS NULL ORDER BY section_name')->fetchAll(PDO::FETCH_ASSOC);
$edit=null; if($admin && isset($_GET['edit'])) { $q=$pdo->prepare('SELECT * FROM vendors WHERE id=? AND deleted_at IS NULL'); $q->execute([(int)$_GET['edit']]); $edit=$q->fetch(PDO::FETCH_ASSOC); }
pageStart($admin?'Vendor Accounts and Rent':'Vendor List'); ?>
<p role="status"><?= h($message) ?></p><?php if($admin): ?><p>Vendors create their own accounts and upload documents. <a href="../auth/register.php">Vendor registration</a> · <a href="collector_approvals.php?role=vendor">Approve registrations</a></p><?php endif ?>
<?php if($edit): ?><form method="post" class="rpms-panel rpms-filters"><?= csrfField() ?><input type="hidden" name="action" value="edit"><input type="hidden" name="id" value="<?= $edit['id'] ?>"><label>Vendor name<input name="vendor_name" value="<?= h($edit['vendor_name']) ?>" required maxlength="150"></label><label>Stall number<input name="stall_number" value="<?= h($edit['stall_number']) ?>" required maxlength="50"></label><label>Section<select name="section_id"><?php foreach($sections as $s): ?><option value="<?= $s['id'] ?>" <?= $edit['section_id']===$s['id']?'selected':'' ?>><?= h($s['section_name']) ?></option><?php endforeach ?></select></label><?php foreach(['monthly_rent','daily_rent','balance'] as $field): ?><label><?= h(ucwords(str_replace('_',' ',$field))) ?><input type="number" name="<?= $field ?>" min="0" max="99999999.99" step="0.01" value="<?= h($edit[$field]) ?>" required></label><?php endforeach ?><label>Next due date<input type="date" name="next_due_date" value="<?= h($edit['next_due_date']) ?>"></label><button class="rpms-button">Save vendor</button></form><?php endif ?>
<form class="rpms-filters"><label>Vendor / Stall / Section<input name="search" value="<?= h($search) ?>"></label><label>Section<select name="section_id"><option value="">All sections</option><?php foreach($sections as $s): ?><option value="<?= $s['id'] ?>" <?= $section===(int)$s['id']?'selected':'' ?>><?= h($s['section_name']) ?></option><?php endforeach ?></select></label><label>Account status<select name="status"><option value="">All</option><?php foreach(['active','inactive','overdue','paid'] as $s): ?><option <?= $status===$s?'selected':'' ?>><?= $s ?></option><?php endforeach ?></select></label><label>Payment status<select name="payment_status"><option value="">All</option><?php foreach(['paid','partial','unpaid','overdue'] as $s): ?><option <?= $paymentStatus===$s?'selected':'' ?>><?= $s ?></option><?php endforeach ?></select></label><button class="rpms-button">Filter</button></form>
<div class="rpms-panel rpms-table-wrap"><table class="rpms-table"><thead><tr><th>Vendor</th><th>Stall</th><th>Section</th><th>Monthly rent</th><th>Daily rent</th><th>Account</th><th>Payment</th><th>Balance</th><th>Next due</th><th>Actions</th></tr></thead><tbody>
<?php $page=max(1,min(max(1,(int)ceil(count($rows)/20)),(int)($_GET['page']??1))); foreach(array_slice($rows,($page-1)*20,20) as $v): ?><tr><td><?= h($v['name']) ?></td><td><?= h($v['stall_number']) ?></td><td><?= h($v['section_name']) ?></td><td>₱<?= number_format($v['monthly_rent'],2) ?></td><td><?= $v['daily_rent']===null?'Needs setup':'₱'.number_format($v['daily_rent'],2) ?></td><td><?= h($v['account_status']) ?></td><td><?= h($v['payment_status']) ?></td><td>₱<?= number_format($v['balance'],2) ?></td><td><?= h($v['next_due_date']??'Not set') ?></td><td><a href="<?= $admin?'payments.php':'collector_history.php' ?>?vendor_id=<?= $v['id'] ?>">History</a> · <a href="<?= $admin?'collect_payment.php':'collector_payments.php' ?>?vendor_id=<?= $v['id'] ?>">Pay</a><?php if($admin): ?> · <a href="?edit=<?= $v['id'] ?>">Edit rent / account</a> <?= removeForm('vendor',(int)$v['id']) ?><?php endif ?></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="10">No matching vendors.</td></tr><?php endif ?></tbody></table><?php pagination(count($rows),$page) ?></div><?php pageEnd(); ?>
